
/* Drop Views */

DROP VIEW SCOTT.EMP_DETAILS_VIEW;
DROP VIEW SCOTT.EMP_VIEW;



/* Drop Tables */

DROP TABLE SCOTT.BONUS CASCADE CONSTRAINTS;
DROP TABLE SCOTT.EMP CASCADE CONSTRAINTS;
DROP TABLE SCOTT.DEPT CASCADE CONSTRAINTS;
DROP TABLE SCOTT.SALGRADE CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE SCOTT.BONUS
(
	ENAME varchar2(10 char),
	JOB varchar2(9 char),
	SAL number,
	COMM number
);


CREATE TABLE SCOTT.DEPT
(
	DEPTNO number(2,0) NOT NULL,
	DNAME varchar2(14 char),
	LOC varchar2(13 char),
	CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO)
);


CREATE TABLE SCOTT.EMP
(
	EMPNO number(4,0) NOT NULL,
	ENAME varchar2(10 char),
	JOB varchar2(9 char),
	MGR number(4,0),
	HIREDATE date,
	SAL number(7,2),
	COMM number(7,2),
	DEPTNO number(2,0),
	CONSTRAINT PK_EMP PRIMARY KEY (EMPNO)
);


CREATE TABLE SCOTT.SALGRADE
(
	GRADE number,
	LOSAL number,
	HISAL number
);



/* Create Foreign Keys */

ALTER TABLE SCOTT.EMP
	ADD CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO)
	REFERENCES SCOTT.DEPT (DEPTNO)
;



/* Create Views */

CREATE OR REPLACE VIEW SCOTT.EMP_DETAILS_VIEW AS SELECT E."EMPNO",E."ENAME",E."JOB",E."MGR",E."HIREDATE",E."SAL",E."COMM",E."DEPTNO",DNAME 부서명,LOC 부서위치
FROM emp e JOIN dept d  ON e.deptno=d.deptno;
CREATE OR REPLACE VIEW SCOTT.EMP_VIEW AS SELECT empno,ename,job,hiredate,deptno
FROM emp;



